### ISSUE TITLE
Cannot find module './app.component.html' from 'app.component.js'

### ISSUE THREAD

**Issue by ghost** [davinkevin/jest#4]
After running ng add and running the tests I get:

```
 Cannot find module './header.component.html' from 'header.component.js'

      53 |     return HeaderComponent;
      54 | }());
    > 55 | export { HeaderComponent };
      56 | //# sourceMappingURL=header.component.js.map

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at dist/out-tsc/src/app/header/header.component.js:55:19
      at Object.<anonymous> (dist/out-tsc/src/app/header/header.component.js:61:2)
```

**Comment by davinkevin** [comment]
I've just done the same on a blank project and on my own and this work fine. 

Could you provide more information (version of project, version of cli, version of angular...) ?

**Comment by davinkevin** [comment]
Any news about this?
